### ISSUE TITLE
Add Content for Tutorial Template

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#10]
## Value statement - a requirement, not a solution
As a **User** 
I need **the instruction**
so that **I can perform the exercise** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-11-16 um 12 15 12](https://user-images.githubusercontent.com/70527121/99246400-8a968580-2805-11eb-96dd-f37b248f352d.png)

## Acceptance criteria
- [x] Image, Titel, Desciption always visible
- [x] Description in list

## Tasks
- [x] Write Content
- [x] Read Tutorial to create Json Script
- [x] Create Json Script for Import
- [x] Import Json to APP
- [x] Import Image to APP
- [x] Check Styling at Devices (ios, android, Versel)
- [x] Add missing Styling
- [x] Testing Devices (ios, android, Versel)
 **Optional** Bug fixing from Testing Devices (ios, android, Versel)

## Size
(medium)
