### ISSUE TITLE
Exercise view / scrolling direction

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#16]
## Value statement - a requirement, not a solution
As a **User** 
I need ** a easy scroll direction**
so that ** is easy to select Tutorials for practics** 

## Description (Text, Scribble, Wireframe, Design)

<img width="318" alt="Bildschirmfoto 2020-11-21 um 08 33 07" src="https://user-images.githubusercontent.com/70527121/99870971-49242280-2bd7-11eb-8bc6-4a1245314a3c.png">

## Acceptance criteria
- [ ] Exercise height = between vh
- [ ] scrolling from left to right

## Tasks
- [x] Create feature branch
- [x] Add CSS for Scrolling
- [x] Add CSS for vh
- [x] Check CSS at Devices (ios, android, vercle)

## Size
medium
