### ISSUE TITLE
Tutorial Template

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#2]
## Value statement - a requirement, not a solution

As a user  **of the MindReset App**
I need **a instructions**
so that **I can to bring my thoughts to rest.**

![Bildschirmfoto 2020-11-16 um 12 15 12](https://user-images.githubusercontent.com/70527121/99246363-79e60f80-2805-11eb-8ab9-070ddd70aa70.png)

## Acceptance criteria
- [x] Image, Titel and Description always visible
- [x] Image, Titel and Description placed in center

## Tasks
- [x] Create Feature Branch
- [x] Create Tutorial Template Component in Story Book
- [x] Add Component to App
- [x] Check styling at devices (ios, android, versel)
- [x] Add missing styling
- [x] Testing devices (ios, android, Versel)
 **Optional** Bug fixing from testing devices (ios, android, versel)

## Size
medium
