### ISSUE TITLE
About Site

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#3]
## Value statement - a requirement, not a solution
As a **User** 
I need **more deep information** 
so that ** i can learn more about mindfulness** 

## Description (Text, Scribble, Wireframe, Design)

<img width="333" alt="Bildschirmfoto 2021-01-09 um 13 19 02" src="https://user-images.githubusercontent.com/70527121/104091368-419b0480-527d-11eb-8321-84ee11779495.png">

## Acceptance criteria
- [x] Footer Navigation with Icon Home and About
- [x] Icon marks current Page

## Tasks
- [x] Create Feature Branch
- [x] Create About Site
- [x] Create Footer Navigatin
- [x] Add About Site Component in Story Book
- [x] Add Component to App
- [x] Check styling at devices (ios, android, versel)
- [x] Add missing styling

    Testing devices (ios, android, Versel)
    Optional Bug fixing from testing devices (ios, android, versel)

## Size
(medium)
