### ISSUE TITLE
Bookmarkt Button

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#4]
## Value statement - a requirement, not a solution
As a **User** 
I need **a Counter Button** 
so that **I can see, how often I did the exercise ** 

## Description (Text, Scribble, Wireframe, Design)

![Bildschirmfoto 2020-11-16 um 12 16 54](https://user-images.githubusercontent.com/70527121/99246480-a69a2700-2805-11eb-99b4-800951bc302c.png)

## Acceptance criteria

- [x] only for one user
- [x] no sharing to other user
- [x] Click on another area, doesn't work

## Tasks
- [x] Create Feature Branch (Name: Task Name)
- [x] Create Button Component in Styleguides
- [x] Add Component to APP
- [x] Check Styling at Devices (ios, android, Versel)
- [x] Add missing Styling
- [x] Testing Devices (ios, android, Versel)
Optional Bug fixing from Testing Devices (ios, android, Versel)

## Size 
lage
