### ISSUE TITLE
Player for audio files

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#5]
## Value statement - a requirement, not a solution
As a **User** 
I need **a audio Player** 
so that **so that I can be guided through the exercises** 

## Description (Text, Scribble, Wireframe, Design)
<img width="307" alt="Bildschirmfoto 2020-11-21 um 08 33 01" src="https://user-images.githubusercontent.com/70527121/99870599-b1253980-2bd4-11eb-88d5-31b4c129063d.png">

## Acceptance criteria
- [x] Play Button
- [x] Stop Button
- [x] Click Play Button start play Tutorial, switch display to stop Icon
- [x] Click Stop Button stop play Tutorial, switch display to play Icon
- [x] Volume control via devices
- [x] Only one soundfile per exercise
- [x] Format: mp3

## Tasks
- [x] Create Feature Branch
- [x] Write Component
- [x] Add Soundfile Name to JSON
- [x] Add Soundfiles to APP
- [x] Add Component to Story book
- [x] Add Component to APP
- [x] Check Devices Styling (ios, android, Versel)
- [x] Add missing Styling
- [x] Testing Devices (ios, android, Versel)
**Optional** Bug fixing from Testing Devices (ios, android, Versel)

## Size
large
