### ISSUE TITLE
App Header

### ISSUE THREAD

**Issue by dajanaheinze** [dajanaheinze/capstone-project#9]
## Value statement - a requirement, not a solution
As a **User** 
I need **the Name from the App** 
so that **I know where I am** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-11-16 um 12 17 41](https://user-images.githubusercontent.com/70527121/99246558-c7627c80-2805-11eb-9c71-d5b8b1084ee3.png)

**Content** 
Image with Logo
Titel Name: mindereset

## Acceptance criteria
- [x] Header ist always visible
- [x] Content scrolling behinde

## Tasks
- [x] Create Feature Branch
- [x] Create Tutorial Template Component in Styleguides
- [x] Add Component to APP
- [x] Check Styling Devices View (ios, android, Versel)
- [x] Add missing Styling
- [x] Testing Devices (ios, android, Versel)
**Optional** Bug fixing from Testing Devices (ios, android, Versel)

## Size
(medium)
